### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by rorypeck** [aslyansky-m/FSTD_SLAM#1]
Hi, long time no update, how about the progress? waiting for yours great work, wish to cooperate to achieve the race

**Comment by aslyansky-m** [comment]
Hi, 
Sorry for the delay, I haven't noticed this.
Thanks!
My work as part of the project is finished, hopefully other students will continue the work, I'm not sure whether they are willing to publish the code.
See this if you are interested:
https://github.com/Microsoft/AirSim/wiki/technion
https://github.com/FSTDriverless/FSTImplementation

Unfortunately I don't have spare time to continue working on this.

Regards
